[package]
name = "marcus-radell-net"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
shuttle-axum = "0.53.0"
shuttle-runtime = "0.53.0"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
